add-validacao

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,7 +40,29 @@ jobs:
             docker run -d --name database-container --network my-net -p 5432:5432 -e POSTGRES_DB=gamesdatabase -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres postgres:16
           fi
     - name: Pull da imagem da aplicação no dockerhub
-      run: docker pull mihkenia/games-deploy:latest
+      run: |
+          echo "Verificando espaço em disco antes de puxar a imagem..."
+          AVAILABLE_SPACE=$(df / | tail -1 | awk '{print $4}')
+          MIN_REQUIRED_SPACE=5000000 # Espaço mínimo em KB (ajuste conforme necessário)
+
+          if [ "$AVAILABLE_SPACE" -lt "$MIN_REQUIRED_SPACE" ]; then
+            echo "Espaço insuficiente em disco. Disponível: $AVAILABLE_SPACE KB. Necessário: $MIN_REQUIRED_SPACE KB."
+            exit 1
+          fi
+
+          for i in {1..3}; do
+            if docker pull mihkenia/games-deploy:latest; then
+              echo "Imagem puxada com sucesso!"
+              break
+            else
+              echo "Falha ao puxar a imagem. Tentativa $i de 3."
+              if [ $i -eq 3 ]; then
+                echo "Todas as tentativas falharam. Abortando."
+                exit 1
+              fi
+              sleep 5 # Espera 5 segundos antes de tentar novamente
+            fi
+          done
     - name: Deletar container do app existente
       run: |
           if docker container inspect app-container &> /dev/null; then
